import json
from datetime import datetime
from typing import Any, Dict

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from app.shared.llm_portkey import chat_complete

router = APIRouter()


class BriefRequest(BaseModel):
    investigation_state: Dict[str, Any]


@router.post("/generate-brief")
async def generate_brief(req: BriefRequest):
    try:
        investigation_state = req.investigation_state or {}
        prompt = f"""You are a senior forensic analyst writing an official investigation brief for the SEBI Enforcement Division.

Based on the following multi-agent investigation results, write a formal "Preliminary Investigation Report"
that could be submitted to SEBI's enforcement team.

Investigation Data:
{json.dumps(investigation_state, indent=2, default=str)}

The report must follow this EXACT structure:

---
PRELIMINARY INVESTIGATION REPORT
Ref: SN-{datetime.now().year}-XXXX
Date: {datetime.now().strftime("%d/%m/%Y")}
Subject: {investigation_state.get("company_name", "Unknown Company")} — Potential Securities Fraud

1. EXECUTIVE SUMMARY
[2–3 sentences. State the verdict, risk score, and top reason.]

2. METHODOLOGY
[1 paragraph. Describe the 5-agent parallel investigation approach.]

3. KEY FINDINGS

3.1 Financial Anomalies
[Bullet points from financial_findings]

3.2 Network & Circular Trading
[Bullet points from graph_findings — mention specific entities if found]

3.3 Regulatory Compliance
[Bullet points from compliance_findings — cite specific SEBI regulations]

3.4 Market Intelligence (News)
[Bullet points from news_findings]

3.5 Management Conduct (Audio Analysis)
[Bullet points from audio_findings]

4. RISK ASSESSMENT
Composite Risk Score: {investigation_state.get("fraud_risk_score", "N/A")}/10
Verdict: {investigation_state.get("verdict", "Unknown")}
[1 paragraph explaining the score.]

5. RECOMMENDED ACTIONS
[3–5 specific recommended next steps for investigators]

6. DISCLAIMER
This report was generated by SathyaNishta AI-assisted investigation platform. All findings
require verification by qualified forensic professionals before regulatory action.
---

Write formally. Use ₹ for currency. Cite sources in brackets like [Source: Neo4j Graph]."""

        response = chat_complete(
            user_prompt=prompt,
            system_prompt="You are an expert forensic compliance report writer. Output plain text only.",
            temperature=0.2,
            metadata={"route": "generate-brief"},
        )
        brief = response.get("content", "") or ""
        return {"brief": brief}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
