"""add_users_table

Revision ID: 6212af7be278
Revises: b0d817509b0d
Create Date: 2026-03-27 14:09:46.351290

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6212af7be278"
down_revision: Union[str, None] = "b0d817509b0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("company", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_premium", sa.Boolean(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("provider_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "verification_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("verification_expires", sa.DateTime(), nullable=True),
        sa.Column("reset_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reset_expires", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_index("idx_regulatory_docs_category", table_name="regulatory_docs")
    op.drop_index(
        "idx_regulatory_docs_embedding",
        table_name="regulatory_docs",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    op.drop_index("idx_regulatory_docs_source", table_name="regulatory_docs")
    op.drop_table("regulatory_docs")
    op.drop_index("idx_audio_company", table_name="audio_transcriptions")
    op.drop_index(
        "idx_audio_embedding",
        table_name="audio_transcriptions",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="ivfflat",
    )
    op.drop_table("audio_transcriptions")
    op.drop_index("idx_fin_company", table_name="financial_filings")
    op.drop_index("idx_fin_doc", table_name="financial_filings")
    op.drop_index("idx_fin_period", table_name="financial_filings")
    op.drop_table("financial_filings")
    op.drop_table("audio_files")
    op.drop_column("investigations", "completed_at")
    op.drop_column("investigations", "context")
    op.drop_column("investigations", "total_tokens_used")
    op.drop_column("investigations", "estimated_completion_time")
    op.drop_column("investigations", "total_execution_time_ms")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "investigations",
        sa.Column(
            "total_execution_time_ms", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "investigations",
        sa.Column(
            "estimated_completion_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "investigations",
        sa.Column(
            "total_tokens_used", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "investigations",
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "investigations",
        sa.Column(
            "completed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "audio_files",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "company_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "call_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("period", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column("call_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("file_key", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("duration_sec", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("transcript", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "participants",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="audio_files_pkey"),
    )
    op.create_table(
        "financial_filings",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "company_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "company_ticker", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("cin", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("period", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "doc_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("filing_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("content_chunk", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("page_number", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "section_name", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.Column("source_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("source_file_key", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="financial_filings_pkey"),
    )
    op.create_index("idx_fin_period", "financial_filings", ["period"], unique=False)
    op.create_index("idx_fin_doc", "financial_filings", ["doc_type"], unique=False)
    op.create_index(
        "idx_fin_company", "financial_filings", ["company_name"], unique=False
    )
    op.create_table(
        "audio_transcriptions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "company_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "company_code", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
        sa.Column("transcript_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("duration_minutes", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("content_chunk", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("chunk_number", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="audio_transcriptions_pkey"),
    )
    op.create_index(
        "idx_audio_embedding",
        "audio_transcriptions",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="ivfflat",
    )
    op.create_index(
        "idx_audio_company", "audio_transcriptions", ["company_name"], unique=False
    )
    op.create_table(
        "regulatory_docs",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column(
            "source", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "category", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "doc_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("content_chunk", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.Column("effective_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="regulatory_docs_pkey"),
    )
    op.create_index(
        "idx_regulatory_docs_source", "regulatory_docs", ["source"], unique=False
    )
    op.create_index(
        "idx_regulatory_docs_embedding",
        "regulatory_docs",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"lists": "100"},
        postgresql_using="ivfflat",
    )
    op.create_index(
        "idx_regulatory_docs_category", "regulatory_docs", ["category"], unique=False
    )
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
