"""init_schema

Revision ID: b0d817509b0d
Revises: 
Create Date: 2026-02-11 10:15:18.882097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b0d817509b0d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "investigations",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("query", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fraud_risk_score", sa.Float(), nullable=True),
        sa.Column("verdict", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("domains", sa.JSON(), nullable=True),
        sa.Column("cross_domain_insights", sa.JSON(), nullable=True),
        sa.Column("evidence_chain", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_investigations_query"), "investigations", ["query"], unique=False)
    op.create_index(op.f("ix_investigations_status"), "investigations", ["status"], unique=False)
    op.create_table(
        "audit_trails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("investigation_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("step_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("input_payload", sa.JSON(), nullable=True),
        sa.Column("output_payload", sa.JSON(), nullable=True),
        sa.Column("model_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_trails_investigation_id"), "audit_trails", ["investigation_id"], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_audio_files_period", table_name="audio_files")
    op.drop_index("idx_audio_files_company", table_name="audio_files")
    op.drop_table("audio_files")
    op.drop_index("idx_financial_filings_doc_type", table_name="financial_filings")
    op.drop_index("idx_financial_filings_period", table_name="financial_filings")
    op.drop_index("idx_financial_filings_ticker", table_name="financial_filings")
    op.drop_index("idx_financial_filings_company", table_name="financial_filings")
    op.drop_table("financial_filings")
    op.drop_index(op.f("ix_audit_trails_investigation_id"), table_name="audit_trails")
    op.drop_table("audit_trails")
    op.drop_index(op.f("ix_investigations_status"), table_name="investigations")
    op.drop_index(op.f("ix_investigations_query"), table_name="investigations")
    op.drop_table("investigations")
    # ### end Alembic commands ###
