"""add_chat_tables

Revision ID: bad8245812e0
Revises: 6212af7be278
Create Date: 2026-03-28 06:58:03.044596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bad8245812e0'
down_revision: Union[str, None] = '6212af7be278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_password_resets_email', table_name='password_resets')
    op.drop_index('idx_password_resets_expires_at', table_name='password_resets')
    op.drop_table('password_resets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='password_resets_pkey'),
    sa.UniqueConstraint('token', name='password_resets_token_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_password_resets_expires_at', 'password_resets', ['expires_at'], unique=False)
    op.create_index('idx_password_resets_email', 'password_resets', ['email'], unique=False)
    # ### end Alembic commands ###
